baseURL = "https://plotem.dev/"
locale = "en-us"
title = "Conor's site"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowToc = true
  ShowCodeCopyButton = true

    [params.homeInfoParams]
      Title = "Hi, I'm Conor! (username is plotem)"
    Content = """
I'm a second year computer science student interested in security, CTFs and building random things!
This site is where I'll put my writeups, projects and notes that I've been accumulating for a while that haven't been published, and anything else I get up to in the future!

Want to know more about me? [Head over to the about page](/about/)!
"""
    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/plotem"

#[[menus.main]]
#  name = "Blog"
#  url = "/blog/"
#  weight = 1
##[[menus.main]]
#  name = "CTF"
#  url = "/ctf/"
#  weight = 2
[[menus.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3
#[[menus.main]]
#  name = "Tags"
#  url = "/tags/"
#  weight = 4
[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 1


[caches]
  [caches.images]
    dir = ':cacheDir/images'
